spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagement
    username: amir
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
server:
  port: 8082